version: '3.7'

services:

  frontend:
    container_name: nl-portal-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:80