name: Build container en push to acr

on:
  push:
    branches:
      - 'feature/**'
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@main

      - name: 'Docker meta'
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.ACR_LOGIN_SERVER }}/zgw/klantportaal

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v1

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v1

      - name: 'Login to acr'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: 'Build and push image'
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=klantportaal
          cache-to: type=inline
