name: Build container en push to acr

on:
  push:
    branches:
      - feature/add-github-workflow
      # - master
  pull_request:
    branches:
      - feature/add-github-workflow
      # - master

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
          
        - name: 'Login to acr'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - name: 'Build and push image'
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: nl-portal:latest
            cache-from: type=registry,ref=user/nl-portal:latest
            cache-to: type=inline